/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.sygus.idea.completion

import com.rainerschuster.sygus.idea.lang.SyGuSLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class SyGuSCompletionContributor extends AbstractSyGuSCompletionContributor {
	new() {
		this(SyGuSLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
