/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.sygus.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class SyGuSIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new SyGuSStandaloneSetupIdea().createInjector
	}

}
