/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.sygus.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class SyGuSIdeaModule extends AbstractSyGuSIdeaModule {
}
