/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.sygus


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SyGuSStandaloneSetup extends SyGuSStandaloneSetupGenerated {

	def static void doSetup() {
		new SyGuSStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
