/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.sygus.idea.lang


class SyGuSFileType extends AbstractSyGuSFileType {
	public static final SyGuSFileType INSTANCE = new SyGuSFileType()
	
	new() {
		super(SyGuSLanguage.INSTANCE)
	}
}
